// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0n0TNPxcpvCd9YREvoQtBa-o99rZzkv0',
    appId: '1:500716010656:web:da8ba362e1942f546f5dc5',
    messagingSenderId: '500716010656',
    projectId: 'online-4f239',
    authDomain: 'online-4f239.firebaseapp.com',
    storageBucket: 'online-4f239.firebasestorage.app',
    measurementId: 'G-SYPGYHSSFG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApuq6Fms7EejhK_H8ld9so2go5EuQGv6c',
    appId: '1:500716010656:android:d512dd6e4a8020526f5dc5',
    messagingSenderId: '500716010656',
    projectId: 'online-4f239',
    storageBucket: 'online-4f239.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYHo2qKsmyii8BjWDWWtLoPBKEQSD-Nxo',
    appId: '1:500716010656:ios:6eb214c635c6bb7b6f5dc5',
    messagingSenderId: '500716010656',
    projectId: 'online-4f239',
    storageBucket: 'online-4f239.firebasestorage.app',
    iosBundleId: 'com.example.online',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYHo2qKsmyii8BjWDWWtLoPBKEQSD-Nxo',
    appId: '1:500716010656:ios:6eb214c635c6bb7b6f5dc5',
    messagingSenderId: '500716010656',
    projectId: 'online-4f239',
    storageBucket: 'online-4f239.firebasestorage.app',
    iosBundleId: 'com.example.online',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0n0TNPxcpvCd9YREvoQtBa-o99rZzkv0',
    appId: '1:500716010656:web:3cccabbfa48564706f5dc5',
    messagingSenderId: '500716010656',
    projectId: 'online-4f239',
    authDomain: 'online-4f239.firebaseapp.com',
    storageBucket: 'online-4f239.firebasestorage.app',
    measurementId: 'G-K4EMZ7KTBL',
  );
}
